<a href="https://colab.research.google.com/github/md-darun-nayeem/Deep_learning_prerequisite/blob/main/Numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types



Numpy Arrays Vs Python Sequences

    NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

    The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

    NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

    A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.



In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [2]:
print(a)

[1 2 3]


In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.random
np.random.random((3,4))

array([[0.78245405, 0.20239501, 0.59983564, 0.10659056],
       [0.8299032 , 0.38311453, 0.48025677, 0.61678086],
       [0.56659276, 0.97937544, 0.60414017, 0.78109014]])

In [11]:
# np.linspace
np.linspace(-10,10,8,dtype=int)

array([-10,  -8,  -5,  -2,   1,   4,   7,  10])

In [12]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
# ndim
a3.ndim

3

In [15]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [17]:
# itemsize
a3.itemsize

8

In [18]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


In [19]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [24]:
a1 = np.random.random((3,3))
a2 = np.round(a1*100)
a1

array([[0.63889199, 0.33481538, 0.50578921],
       [0.13600932, 0.50111247, 0.04445509],
       [0.89552839, 0.17116559, 0.30547025]])

In [25]:
a2

array([[64., 33., 51.],
       [14., 50.,  4.],
       [90., 17., 31.]])

In [26]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a2,axis=0)

array([90., 50., 51.])

In [27]:
np.min(a2,axis=0)

array([14., 17.,  4.])

In [28]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a2,axis=0)

array([80640., 28050.,  6324.])

In [29]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[52., 65., 82.],
       [35., 84., 80.],
       [49., 77., 74.]])

In [30]:
# mean/median/std/var
np.var(a1,axis=1)

array([150.88888889, 493.55555556, 157.55555556])

In [31]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.98662759,  0.82682868,  0.31322878],
       [-0.42818267,  0.73319032, -0.99388865],
       [-0.95375265,  0.99952016, -0.98514626]])

In [32]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
# log and exponents
np.exp(a1)

array([[3.83100800e+22, 1.69488924e+28, 4.09399696e+35],
       [1.58601345e+15, 3.02507732e+36, 5.54062238e+34],
       [1.90734657e+21, 2.75851345e+33, 1.37338298e+32]])

In [34]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[92.,  8., 15.],
       [17., 17., 34.]])

In [35]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[74., 66., 66.],
       [96., 85., 21.]])

In [36]:
# Indexing and Slicing

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a2[1,0]

4

In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
a3[1,0,1]

5

In [40]:
a1[2:5:2]

array([2, 4])

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[0,:]

array([0, 1, 2, 3])

In [43]:
a2[:,2]

array([ 2,  6, 10])

In [44]:
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [46]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [47]:
a2[1,::3]

array([4, 7])

In [49]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [51]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [52]:
a3[0,1,:]

array([3, 4, 5])

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [57]:
for i in a3:
    print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [58]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [59]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [62]:
# ravel : converts multidimension array to single dimension
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
# np.hstack : to compress two array--> vstack,hstack
# splitting : hsplit, vsplit